#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GoTour.Droid.Resource", IsApplication=true)]

namespace GoTour.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020001
			public const int backbutton = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int backgroundLogin = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int backgroundPlaceManager = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int background_showtour = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int background_tourview = 2130837509;
			
			// aapt resource value: 0x7F020000
			public const int backPackIcon = 2130837504;
			
			// aapt resource value: 0x7F020006
			public const int bellIcon = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int bookmark = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int calendarIcon = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int clockIcon = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int defaultUser = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int delete = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int deleteIcon = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int durationicon = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int editIcon = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int eyeIcon = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int eyeOffIcon = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int filtericon = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int flagOutlineIcon = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int googleLogin = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int heartIcon = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int heartOutlineIcon = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int homeIcon = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int homeOutlineIcon = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int invoiceIcon = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int locationIcon = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int love_red = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int love_white = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int manager = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int menuIcon = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int moneyIcon = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int occuringTourIcon = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int orderedTourIcon = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int passengerIcon = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int planeIcon = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int scoreicon = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int searchIcon = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int shoppingcartIcon = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int sorticon = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int starttimeicon = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int thuc = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int tickIcon = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int tourIcon = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int trashIcon = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int userOutlineIcon = 2130837548;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
